### ISSUE TITLE
Simple Sample

### ISSUE THREAD

**Issue by bmfs** [jeremyfa/spine-hx#1]
Could you provide a simple sample of how to use the lib?

**Comment by Beeblerox** [comment]
There is only one sample on how to use it (as far as i know) and it's using flixel https://github.com/jeremyfa/flixel-spine-hx

you'll need to write your own renderer to make it work with openfl / nme or any other framework (or you can just port flash renderer from official spine runtime library)

**Comment by jeremyfa** [comment]
Basic flash rendering is also ported to Haxe: https://github.com/jeremyfa/spine-hx/tree/master/spine/flash (even though I didn't really test it, but should work).

Anyway, as the runtime API is the same as the official as3 runtime, you can also see how it has been implemented for starling as well: https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-starling/spine-starling/src/spine/starling

**Comment by jeremyfa** [comment]
Closing this as there is not much to add :)
