### ISSUE TITLE
Spine 3.7 is out, update converter and generate spine-hx 3.7

### ISSUE THREAD

**Issue by jeremyfa** [jeremyfa/spine-hx#15]
Spine 3.7 was released a few days ago. It is expected that the converter will break as this is a new version with major changes, but it should not be too difficult to update it and make it work again.

**Comment by jeremyfa** [comment]
Some update on this:

There is a [new branch 3.7](https://github.com/jeremyfa/spine-hx/tree/3.7) with:

* An updated converter that generates the Spine 3.7 runtime haxe codebase
* SkeletonBinary.hx that has been removed for now because it was breaking compilation @Beeblerox feel free to make a pull request with an updated version!

Currently the code compiles fine but is untested. I am [hitting some issues](http://fr.esotericsoftware.com/forum/ERROR-Missing-output-path-when-exporting-from-command-line-11425) that prevent me to do extensive tests for now but I hope this will be sorted out soon.

Will keep updating this issue when I have more news!

**Comment by Beeblerox** [comment]
@jeremyfa i'll try to update binary loader ASAP

**Comment by jeremyfa** [comment]
@Beeblerox no worries, at the moment 3.6 is still the default branch anyway :)

**Comment by jeremyfa** [comment]
Will resume work on this once [this issue](https://github.com/EsotericSoftware/spine-editor/issues/434) is resolved

**Comment by Beeblerox** [comment]
@jeremyfa here is pull request with updated binary loader for Spine 3.7 https://github.com/jeremyfa/spine-hx/pull/16

**Comment by jeremyfa** [comment]
CLI issue mentioned above should be fixed by now, will try to test 3.7 (then 3.8) a bit!

**Comment by Beeblerox** [comment]
@jeremyfa i think that spine's binary format has changed, will try to update it next week

**Comment by jeremyfa** [comment]
Yes, but it will be difficult to test it as for now I didn't try to convert official runtime to branch 3.8! :)

**Comment by jeremyfa** [comment]
Runtime v3.7 is now published on haxelib. Closing this.
