### ISSUE TITLE
Spine 3.8 is out, update converter and generate spine-hx 3.8

### ISSUE THREAD

**Issue by jeremyfa** [jeremyfa/spine-hx#17]
Current status:

- Spine 3.6 haxe branch is the most stable and supported one on this day (using it daily)
- Spine 3.7 haxe branch should work, but I didn't test it myself yet (need to finish a big project based on 3.6 by the end of the year first). I am actually interested to know if other haxe devs are using it?
- Spine 3.8 has been released. Converter should be updated to support it, which should not be very difficult. Will try to free some time to do it soon.

**Comment by digibo** [comment]
Our preliminary tests show that updating from 3.6 to 3.7 works without issues for us, but I don't think we are using most of Spine's features beyond the basics.

**Comment by jeremyfa** [comment]
There is now a 3.8 branch with updated runtime.

Feel free to let me know here if it the updated runtime works for you!

**Comment by jeremyfa** [comment]
More updates:

Runtime 3.8 seems to work fine on the game I am working on.

The game is a pretty big one with a lot of 2d mesh deformations & constraints, so that's a pretty good sign :)

**Comment by jeremyfa** [comment]
Runtime 3.8 is now published on haxelib. Closing this issue but feel free to give feedback if you have any.

@Beeblerox I had to remove SkeletonBinary like last time, but your pull request to provide an updated one is welcomed! (Didn't have time to work on converting that automatically at the moment)

**Comment by Beeblerox** [comment]
@jeremyfa i will try to do it next week or so
