### ISSUE TITLE
MathUtils.signum should return zero if argument is zero

### ISSUE THREAD

**Issue by digibo** [jeremyfa/spine-hx#8]
Currently MathUtils.signum behaves differently from Java's [Math.signum](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html) which returns zero if the argument is zero. This causes AnimationState.applyRotateTimeline to sometimes add additional 360 degrees of rotation when mixing animations and possibly other problems.

**Comment by jeremyfa** [comment]
Thanks for reporting!

This is now fixed in master.
